language: elixir

elixir:
  - 1.7
  - 1.8
  - 1.9
  - 1.10.3

otp_release:
  - 19.0
  - 20.0
  - 21.0
  - 22.0
  - 23.0

matrix:
  exclude:
    - elixir: 1.7
      otp_release: 23.0
    - elixir: 1.8
      otp_release: 19.0
    - elixir: 1.8
      otp_release: 23.0
    - elixir: 1.9
      otp_release: 19.0
    - elixir: 1.9
      otp_release: 23.0
    - elixir: 1.10.3
      otp_release: 19.0
    - elixir: 1.10.3
      otp_release: 20.0

env:
  global:
    - ELIXIR_ASSERT_TIMEOUT=2000

before_script:
  - mix deps.get

script:
  - mix test
